Repository Michael-Santana/devops-aula07, pull requests merged in 2018-03, with the labels that each got.

#5 V1.0 analise
  docs/requisitos.md
Labels: análise

#6 Integrar implementação v1.0
  src/jogovelha.py
Labels: Programação

#8 Create arquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#9 Integrar testes v1.0
  src/teste_jogar.py
  src/testes_inic.py
Labels: testes

#10 Update arquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#11 Update requisitos.md
  docs/requisitos.md
Labels: análise

#12 Gerar release v1.0
  docs/arquitetura.md
  docs/requisitos.md
  src/jogovelha.py
  src/teste_jogar.py
  src/testes_inic.py
Labels: Operações

#17 Update requisitos.md
  docs/requisitos.md
Labels: análise

#18 Integrar implementação v1.0
  src/jogovelha.py
  src/tabuleiro.py
Labels: Programação

#19 Update arquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#20 Guivmiotto patch 1
  src/teste_jogar.py
  src/testes_inic.py
Labels: testes
